### PR TITLE
Add support for Rails view components

### PR DESCRIPTION
**Pull request by budu**
View components are using a block to be able to render slots.

### CODE REVIEW

**Comment by tagliala** [comment]
Thanks, can you please add a spec?

**Comment by budu** [comment]
Done. 

I wasn't sure how to fake the component here, so I went with an anonymous class.

**Comment by javierjulio** [comment]
@budu can you please provide more information about what you are trying to do here and how this would be used? It's not clear if you are referring to view components as a general thing from Arbre's perspective or something specific to Rails. We'll also include this PR in the release notes so it would help to have background and examples on what this provides. Thank you.

**Comment by budu** [comment]
In my use case, it's to support ViewComponent's [slots feature](https://viewcomponent.org/guide/slots.html). For example:

```ruby
render BlogComponent.new do |component|
  component.with_header do
    link_to "My blog", root_path
  end
  BlogPost.all.each do |blog_post|
    component.with_post do
      link_to blog_post.name, blog_post.url
    end
  end
end
```

This allows the `render` helper to pass-in the view context along with the block to the component.

ViewComponent was using a monkey patch before Rails 6.1. The `render` helper from ActionView was changed in [this commit](https://github.com/rails/rails/commit/c221b5b448569771678279216360460e066095a7) to accomodate the `render_in` back in 2019.

**Review by javierjulio — APPROVED** [review]
Thanks!

**Pull request merged**
