### PR TITLE
Add Ruby 3.1.0 to CI matrix

### PR DESCRIPTION
**Pull request by alejandroperea**
Testing Arbre with the latest Ruby version (3.1.0)

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Thanks so much @alejandroperea for your recent help.

Regarding the failures, I've been there. I think you need to expire the bundler cache to make sure everything gets installed from scratch and the `matrix` gem is picked up. It was a default gem in previous versions, so it's not present in the gems cache from Ruby 3.0, but in Ruby 3.1 it is a default gem, so it needs to be installed explicitly. IMO this is an issue in bundler, that should be still installing default gems depended on explicitly. I'll see what we can do on the Bundler side.

**Comment by alejandroperea** [comment]
@deivid-rodriguez I think I've fixed it.

For the Ruby 3.1 and Rails 6.1 combination, I've updated capybara to its latest version (3.36.0) that comes with matrix as a dependency.

For the Ruby 3.1 and Rails 7 combination, I think the problem was one of the net-* gems, that comes by default in Rails 7.0.1 (and not loaded by default in Ruby 3.1 I think)

Now all tests all passing. Could you have a look?

**Comment by deivid-rodriguez** [comment]
Oh, you're right, then there's no issue in Bundler indeed, I thought the matrix gem was already in the lockfile, yet not installed on Ruby 3.0, but it seems not the case 👍. This looks good to me!

**Review by javierjulio — APPROVED** [review]
Thank you! ❤️

**Pull request merged**
