### PR TITLE
Run tests against Rails 6 and fix deprecations

### PR DESCRIPTION
**Pull request by deivid-rodriguez**

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
I plan to release a minor fixing  ruby 2.7 deprecation warnings.

But I wanted to make sure tests run cleanly on Rails 6 before working on that.

**Comment by javierjulio** [comment]
Ok great, sounds good to me, thanks!

**Comment by deivid-rodriguez** [comment]
No, was going to request a review from you actually :). Thanks!

**Comment by javierjulio** [comment]
Ha beat you to it. 😏 No problem!

**Pull request merged**
